Fix neovim release link
AstroNvim/astronvim.github.io pull request #60
Opened 2023-03-11 08:16 UTC by baptisteArno

2023-03-11 12:18 UTC, mehalter requested changes
Thanks for catching this broken link! Could you please just fix the one suggestion to the link text?

2023-03-11 12:18 UTC, mehalter commented on docs/intro.md
> +- [Neovim (_Not_ including nightly)](https://github.com/neovim/neovim/releases/tag/stable)
```suggestion
- [Neovim 0.8+ (_Not_ including nightly)](https://github.com/neovim/neovim/releases/tag/stable)
```

Could you please revise this to say

2023-03-12 01:42 UTC, mehalter approved these changes
I made a small revision and this looks great thanks for catching this broken link!

2023-03-12 01:42 UTC, merged

2023-03-12 07:53 UTC, baptisteArno commented
Hey thanks, sorry was not available yesterday to apply the changes 🙏