Fix outdated unattended install command and syntax
AstroNvim/astronvim.github.io pull request #99
Opened 2023-07-18 07:52 UTC by medv

Finishes https://github.com/AstroNvim/astronvim.github.io/pull/63

2023-07-18 13:26 UTC, mehalter requested changes
Thanks for catching this! I did some testing and it does seem like we don't want to have the autocmd. In this case qw can also do `+q` instead of the full `-c 'quitall'`

2023-07-18 13:26 UTC, mehalter commented on docs/Recipes/unattended_install.md
> +3. `nvim --headless -c 'quitall'`
```suggestion
3. `nvim --headless +q`
```

2023-07-19 04:04 UTC, medv commented
This answered a couple questions actually, thanks!

2023-07-19 10:03 UTC, mehalter approved these changes
Looks great! Thanks :D

2023-07-30 11:42 UTC, merged